# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from fileinput import close
from hashlib import new
import random as rd
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import  Qt,QMimeData
from PyQt5.QtWidgets import QApplication,QWidget,QPushButton
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import * 
from PyQt5.QtGui import * 
import sys





class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-40, -40, 891, 521))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("WELCOME.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 475, 381, 61))
        self.label_2.setText("")
        self.label_2.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(5,230,1000,241))
        self.label_3.setFont(QFont("Arial",20))
        self.label_3.setText("")
        self.label_3.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(240, 475, 381, 61))
        self.label_4.setText("")
        self.label_4.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 475, 381, 61))
        self.label_5.setText("")
        self.label_5.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 470, 171, 71))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setVisible(False)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 470, 171, 71))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setVisible(False)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 470, 171, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setVisible(False)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(620, 530, 171, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(620, 490, 171, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSARCHEVI = QtWidgets.QMenu(self.menubar)
        self.menuSARCHEVI.setObjectName("menuSARCHEVI")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTRAPEZOID = QtWidgets.QAction(MainWindow)
        self.actionTRAPEZOID.setObjectName("actionTRAPEZOID")
        self.actionRectangle = QtWidgets.QAction(MainWindow)
        self.actionRectangle.setObjectName("actionRectangle")
        self.actionSquare = QtWidgets.QAction(MainWindow)
        self.actionSquare.setObjectName("actionSquare")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.menuFile.addAction(self.actionNew)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menuSARCHEVI.addAction(self.actionTRAPEZOID)
        self.menuSARCHEVI.addAction(self.actionRectangle)
        self.menuSARCHEVI.addAction(self.actionSquare)
        self.menubar.addAction(self.menuSARCHEVI.menuAction())
       

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.actionTRAPEZOID.triggered.connect(lambda: self.show_trap("TRAPEZOID.jpg"))
        self.actionSquare.triggered.connect(lambda: self.show_trap2("SQUARE.png"))
        self.actionRectangle.triggered.connect(lambda: self.show_trap3("RECTANGLE.png"))
        self.actionNew.triggered.connect(lambda: self.new2())
        self.pushButton.clicked.connect(self.TRAPAREA)
        self.pushButton_2.clicked.connect(self.RECTAREA)
        self.pushButton_3.clicked.connect(self.SQUAREAREA)
        self.pushButton_4.clicked.connect(MainWindow.close)
        self.pushButton_5.clicked.connect(self.Def)

        
       
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "TRAPEZOID Area=?"))
        self.pushButton_2.setText(_translate("MainWindow", "Rectangle Area=?"))
        self.pushButton_3.setText(_translate("MainWindow", "Square Area=?"))
        self.pushButton_4.setText(_translate("MainWindow", "Close"))
        self.pushButton_5.setText(_translate("MainWindow", "Default"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.menuSARCHEVI.setTitle(_translate("MainWindow", "SARCHEVI"))
        self.actionTRAPEZOID.setText(_translate("MainWindow", "Trapezoid"))
        self.actionRectangle.setText(_translate("MainWindow", "Rectangle"))
        self.actionSquare.setText(_translate("MainWindow", "Square"))
    def Def(self):
        self.pushButton.setVisible(False)
        self.pushButton_2.setVisible(False)
        self.pushButton_3.setVisible(False)
        self.label.setPixmap(QtGui.QPixmap("WELCOME.png"))
        self.label.setGeometry(QtCore.QRect(-40, -40, 891, 521))

    def show_trap(self,photo):
        self.label_2.setText("")
        self.label_3.setText("")
        
        self.pushButton.setVisible(True)
        self.pushButton_2.setVisible(False)
        self.pushButton_3.setVisible(False)
        self.label.setPixmap(QtGui.QPixmap(photo))
        self.label.adjustSize()
    
    def show_trap2(self,photo):
        self.label_2.setText("")
        self.label_3.setText("")
        self.pushButton_2.setVisible(False)
        self.pushButton.setVisible(False)
        self.pushButton_3.setVisible(True)
        self.label.setPixmap(QtGui.QPixmap(photo))
        self.label.adjustSize()
    
    def show_trap3(self,photo):
        self.label_2.setText("")
        self.label_3.setText("")
        self.pushButton.setVisible(False)
        self.pushButton_2.setVisible(True)
        self.pushButton_3.setVisible(False)
        self.label.setPixmap(QtGui.QPixmap(photo))
        self.label.adjustSize()
    def new(self,text):
        self.label_2.setText(text)
     
    
    def new2 (self):
        msg=QMessageBox()
        msg.setWindowTitle("NEW WINDOW ")
        msg.setIcon(QMessageBox.Question)
        msg.setStandardButtons(QMessageBox.Cancel| QMessageBox.Retry | QMessageBox.Ignore)
        msg.setDefaultButton(QMessageBox.Retry)
        msg.setInformativeText("NEW WAS KLICKED")
        msg.setDetailedText("There is no time for new things. contact back in 2023")

        msg.buttonClicked.connect(self.popup_button)
        x=msg.exec_()

    def popup_button(self,i):
        print(i.text())        
        
     
 
    def TRAPAREA(self):
        
        self.fudze1 = rd.randrange(1,10)
        self.fudze2 = rd.randrange(1,10)
        self.simagle = rd.randrange(1,10)
        Area=(self.fudze1 + self.fudze2) / 2 * self.simagle
        self.label_2.setText("Area of the Trapezoid = " + str(Area))
        self.label_3.setText("FUDZE1=  "+str(self.fudze1)+"  /  " +"FUDZE2=" +str(self.fudze2) + "  /  " +"SIMAGLE="+str(self.simagle))
        

    def RECTAREA(self):
        self.fudze1 = rd.randrange(1,10)
        self.fudze2 = rd.randrange(1,10)
        self.simagle = rd.randrange(1,10)
        Area=self.fudze1*self.fudze2
        self.label_2.setText("Area of the RECTANGLE = " + str(Area))
        self.label_3.setText("a =  "+str(self.fudze1)+"  /  " +"b =" +str(self.fudze2) )
    def SQUAREAREA(self):
        self.fudze1 = rd.randrange(1,10)
        self.fudze2 = rd.randrange(1,10)
        self.simagle = rd.randrange(1,10)
        Area=self.fudze1**2
        self.label_2.setText("Area of the SQUARE = " + str(Area))
        self.label_3.setText("GVERDI =  "+str(self.fudze1))
       
         
    
    
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
